### ISSUE TITLE
Config file not present

### ISSUE THREAD

**Issue by awsshaun** [aws-samples/amazon-sagemaker-llm-on-video-audio#8]
not sure why I am getting this error from your code
when i run the data_preperation.py, second workbook step
<img width="800" alt="Screenshot 2023-09-16 at 11 58 15 am" src="https://github.com/aws-samples/amazon-sagemaker-llm-on-video-audio/assets/109882259/6c678523-55ce-4915-8949-41cc210eb64a">

**Comment by guanghui0607** [comment]
@awsshaun it seems to happen for all new instances or or studio server kernels since April this year, but it won't affect the execution of the script.

**Comment by awsshaun** [comment]
thankyou

Shaun Keating
Snr Manager, Solution Architects, Financial Services
Amazon Web Services

+61 434 410 783 - mobile
Please note I work outside of traditional business hours as that works for me. If you have received this email after hours, I do not expect a response before the next business day.

[signature_1083371959][signature_2939025925][signature_227648429][signature_1956530583][signature_4083939803]


From: "Gordon Wang (Guanghui Wang)" ***@***.***>
Reply to: aws-samples/amazon-sagemaker-llm-on-video-audio ***@***.***>
Date: Saturday, 23 September 2023 at 1:19 pm
To: aws-samples/amazon-sagemaker-llm-on-video-audio ***@***.***>
Cc: "Keating, Shaun" ***@***.***>, Mention ***@***.***>
Subject: Re: [aws-samples/amazon-sagemaker-llm-on-video-audio] Config file not present (Issue #8)


@awsshaun<https://github.com/awsshaun> it seems to happen for all new instances or or studio server kernels since April this year, but it won't affect the execution of the script.
